site_name: Wikidoc
repo_name: "codium9/wikidoc"
repo_url: https://github.com/codium9/wikidoc
site_url: https://codium9.github.io/wikidoc
edit_uri: edit/main/docs/

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.sections
    - content.code.copy
    - content.code.annotate
    - content.action.edit
    - content.action.view

  palette:
    primary: "indigo"
    accent: "lime"

  include_sidebar: true

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true

nav:
  - Welcome:
      - Welcome: "index.md"
#      - How it works: "how-it-works.md"
#      - Troubleshooting: "troubleshooting.md"
#      - kubectl plugin: "kubectl-plugin.md"
      - Linux:
#      - Installation Guide: "deploy/index.md"
#      - Bare-metal considerations: "deploy/baremetal.md"
#      - Role Based Access Control (RBAC): "deploy/rbac.md"
#      - Upgrade: "deploy/upgrade.md"
#      - Hardening guide: "deploy/hardening-guide.md"
      - Windows:
#      - NGINX Configuration:
#          - Introduction: "user-guide/nginx-configuration/index.md"
#          - Basic usage: "user-guide/basic-usage.md"
#          - Annotations: "user-guide/nginx-configuration/annotations.md"
#          - ConfigMap: "user-guide/nginx-configuration/configmap.md"
#          - Custom NGINX template: "user-guide/nginx-configuration/custom-template.md"
#          - Log format: "user-guide/nginx-configuration/log-format.md"
#      - Command line arguments: "user-guide/cli-arguments.md"
#      - Custom errors: "user-guide/custom-errors.md"
#      - Default backend: "user-guide/default-backend.md"
#      - Exposing TCP and UDP services: "user-guide/exposing-tcp-udp-services.md"
#      - Exposing FCGI services: "user-guide/fcgi-services.md"
#      - Regular expressions in paths: user-guide/ingress-path-matching.md
#      - External Articles: "user-guide/external-articles.md"
#      - Miscellaneous: "user-guide/miscellaneous.md"
#      - Prometheus and Grafana installation: "user-guide/monitoring.md"
#      - Multiple Ingress controllers: "user-guide/multiple-ingress.md"
#      - TLS/HTTPS: "user-guide/tls.md"
#      - Third party addons:
#          - ModSecurity Web Application Firewall: "user-guide/third-party-addons/modsecurity.md"
#          - OpenTracing: "user-guide/third-party-addons/opentracing.md"
      - Code:
#      - Introduction: "examples/index.md"
#      - Prerequisites: "examples/PREREQUISITES.md"
#      - Sticky Sessions: "examples/affinity/cookie/README.md"
#      - Auth:
#          - Basic Authentication: "examples/auth/basic/README.md"
#          - Client Certificate Authentication: "examples/auth/client-certs/README.md"
#          - External Basic Authentication: "examples/auth/external-auth/README.md"
#          - External OAUTH Authentication: "examples/auth/oauth-external-auth/README.md"
#      - Customization:
#          - Configuration Snippets: "examples/customization/configuration-snippets/README.md"
#          - Custom Configuration: "examples/customization/custom-configuration/README.md"
#          - Custom Errors: "examples/customization/custom-errors/README.md"
#          - Custom Headers: "examples/customization/custom-headers/README.md"
#          - External authentication: "examples/customization/external-auth-headers/README.md"
#          - Custom DH parameters for perfect forward secrecy: "examples/customization/ssl-dh-param/README.md"
#          - Sysctl tuning: "examples/customization/sysctl/README.md"
#      - Docker registry: "examples/docker-registry/README.md"
#      - gRPC: "examples/grpc/README.md"
#      - Multi TLS certificate termination: "examples/multi-tls/README.md"
#      - Rewrite: "examples/rewrite/README.md"
#      - Static IPs: "examples/static-ip/README.md"
#      - TLS termination: "examples/tls-termination/README.md"
#      - Pod Security Policy (PSP): "examples/psp/README.md"
      - Middleware:
      - Database:
      - Docker:
      - Terraform:
      - Savegarde:
#      - Getting Started: "developer-guide/getting-started.md"
#      - Code Overview: "developer-guide/code-overview.md"  
