site_name: Wikidoc
repo_name: "codium9/wikidoc"
repo_url: https://github.com/codium9/wikidoc
site_url: https://codium9.github.io/wikidoc
edit_uri: edit/main/docs/

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - header.autohide
    - content.code.copy
    - content.code.annotate
    - content.action.edit
    - content.action.view
    - toc.follow
    - toc.integrate
    - navigation.footer

  palette:
    primary: "indigo"
    accent: "amber"

  include_sidebar: true

plugins:
  - search:
      lang: fr
  - git-revision-date-localized:
      enable_creation_date: true

nav:
  - Welcome:
    - Welcome: "index.md"
  - BareMetal:
    - Linux:
      - Crontab: "Linux/Crontab.md"
      - Firewall: "Linux/Firewall.md"
      - LVM: "Linux/LVM.md"
      - Shell: "Linux/Shell.md"
      - Init: "Linux/Init.md"
      - OsCommand: "Linux/Command.md"
      - User/Group: "Linux/User-Group.md"
      - Vim: "Linux/Vim.md"
    - Windows:
      - Win_stuff: "Microsoft/Windows.md"
  - Code:
    - Python: "Code/Python.md"
    - Perl: "Code/Perl.md"
  - Middleware:
    - Apache: "Middleware/Apache.md"
    - Postfix: "Middleware/Postfix.md"
  - Security:
    - OpenSSL: "Security/OpenSSL.md"
  - Database:
    - DB2: "Database/DB2.md"
    - Oracle: "Database/Oracle.md"
    - Sqlserver: "Database/Sqlserver.md"
  - Containers:
    - Docker: "Docker/Containers.md"
  - Terraform:
    - Terraform: "Terraform/Terraform.md"
  - Deprecated:
    - AIX: "Unix/Aix.md"
    - TSM: "Backup/TSM.md"
    - Weblogic: "Middleware/Weblogic.md"
    - Websphere: "Middleware/Websphere.md"
    - ControlM: "Scheduler/ControlM.md"